### ISSUE TITLE
Add midnight theme to HACS

### ISSUE THREAD

**Issue by tjorim** [pho3nixf1re/home-assistant-theme-midnight#1]
HACS repo: https://github.com/custom-components/hacs
Info about structure: https://hacs.netlify.com/developer/theme/

Only `info.md` seems to be missing, example here: https://github.com/ludeeus/theme-hacs/blob/master/info.md

How to add as default repo: https://hacs.netlify.com/developer/include_default_repositories/
Actual place to submit it: https://github.com/custom-components/hacs/blob/data/repositories/theme

**Comment by pho3nixf1re** [comment]
I have [added support](https://github.com/pho3nixf1re/home-assistant-theme-midnight/commit/2333614c0c78831f3a0555c093e7d51487570336) and opened a PR in the HACS repo data.

**Comment by pho3nixf1re** [comment]
The main repo is now https://github.com/home-assistant-community-themes/midnight which is included out of the box with HACS.
